---
- name: Warn about selinux reboot
  debug:
    msg: "Изменена конфигурация SELinux. Для внесения постоянных изменений требуется перезагрузка."
  listen: "Restart selinux"

- name: Restart system if required
  reboot:
    msg: "Ansible: SELinux configuration changed"
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
  when: selinux_require_reboot | bool
  listen: "Restart selinux"