---
galaxy_info:
  author: Vlada Derina
  description: Role description
  company: Your Company
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions:
        - 7
        - 8
    - name: Ubuntu
      versions:
        - bionic
        - focal
    - name: Debian
      versions:
        - buster
        - bullseye
  galaxy_tags:
    - system
    - configuration

dependencies: []